# Generated by Django 4.2.2 on 2023-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_listing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FN', 'Fashion'), ('TY', 'Toys'), ('EL', 'Electronics'), ('HM', 'Home'), ('SP', 'Sport')], default='FN', max_length=2),
        ),
    ]
