# Generated by Django 4.2.2 on 2023-07-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Appliances', 'Appliances'), ('Tech', 'Tech'), ('Gaming', 'Gaming'), ('Fashion', 'Fashion'), ('Sports and Fitness', 'Sports and Fitness'), ('Other', 'Other'), ('Hygiene and Medicine', 'Hygiene and Medicine'), ('Stationery', 'Stationery'), ('Decor', 'Decor'), ('Furniture', 'Furniture'), ('Cars and Mechanical Things', 'Cars and Mechanical Things'), ('Tools', 'Tools')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_listings', to='auctions.category'),
        ),
    ]
