# Generated by Django 4.2.2 on 2023-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
