# Generated by Django 4.2.2 on 2023-07-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_comment_watchlist_delete_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Appliances', 'Appliances'), ('Tech', 'Tech'), ('Gaming', 'Gaming'), ('Fashion', 'Fashion'), ('Sports and Fitness', 'Sports and Fitness'), ('Other', 'Other'), ('Hygiene and Medicine', 'Hygiene and Medicine'), ('Stationery', 'Stationery'), ('Decor', 'Decor'), ('Furniture', 'Furniture'), ('Cars and Mechanical Things', 'Cars and Mechanical Things'), ('Tools', 'Tools')], max_length=35, null=True),
        ),
    ]
